name: part3
channels:
  - gurobi
  - malavp
  - conda-forge
  - defaults
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - cloudpickle=3.1.1
  - contourpy=1.3.2
  - cpython=3.13.3
  - cycler=0.12.1
  - fmt=11.1.4
  - fonttools=4.58.0
  - freetype=2.13.3
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gurobi=12.0.2
  - heyoka=7.3.0
  - heyoka.py=7.3.3
  - icu=75.1
  - joblib=1.5.1
  - kiwisolver=1.4.7
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.5
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflint=3.2.2
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsqlite=3.49.2
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.5
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mppp=2.0.0
  - munkres=1.1.4
  - narwhals=1.44.0
  - ncurses=6.5
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openssl=3.5.0
  - packaging=25.0
  - pillow=11.2.1
  - pip=25.1.1
  - plotly=6.2.0
  - pthread-stubs=0.4
  - pybind11-abi=4
  - pyparsing=3.2.3
  - python=3.13.3
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - qhull=2020.2
  - readline=8.2
  - scikit-learn=1.7.0
  - scipy=1.15.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.8
  - spdlog=1.15.3
  - sympy=1.14.0
  - tbb=2022.1.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.1
  - tzdata=2025b
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7